### ISSUE TITLE
Why should `start_logits` be multiplied by `rational_logits`?

### ISSUE THREAD

**Issue by JeremySun1224** [NTU-SQUAD/transformers-coqa#3]
Hi, thank you for your very good work. 

There is a place in `modeling_bert.py` that I don't quite understand, [line 68](https://github.com/NTU-SQUAD/transformers-coqa/blob/b12ca2d9e04c96fca5169567a4cdd19e18fa81a0/model/modeling_bert.py#L68). 

That is `start_logits, end_logits = start_logits * rational_logits, end_logits * rational_logits`

Why should `start_logits` be multiplied by `rational_logits`? and what are the `rational_logits` here? Is it necessary?

Looking forward to your reply, thank you!🤗

**Comment by naseeihity** [comment]
For the rational part, your can refer to [this paper](https://arxiv.org/abs/1909.10772)(part 3.2)

**Comment by JeremySun1224** [comment]
Thanks for your reply, I know what `rational_logits` means, but what I don't understand is why `start_logits` can be multiplied with `rational_logits`, is there any theoretical basis for this?
